---
title: "SCC243 Sustainable Computing Labs"
---

Weekly lab tasks for SCC.243 Sustainable Computing.

## Weekly tasks build up a portfolio of assessment

Each week there is:

1. a task to do in lab
2. sometimes I'll set a recommended essential reading
3. there may be additional tasks (such as short pieces of reflective writing, in blog post format, especially at the start and end of the course)

All the writing will be conducted in markdown (`.md` files) and submitted via a private github repository that is shared with the course convenor '`@friday`', that you create **in the week 1 lab!**

The labs are anticipated to be as follows:

| Week | Lab | See details (link) |
| ---  | --- | --- |
| 1 | Setup research task, github; opening reflective statement | [week1](week1/week1-task.html) |
| 2 | My digital footprint survey/ photos | [week2](week2/week2-task.html) |
| 3 | Workload footprint estimation | [week3](week3/week3-task.html) |
| 4 | Measurement lab | <!-- [week4](week4) --> |
| 5 | Green AI measurement lab | <!-- [week5](week5) --> |
| 6 | Topic & reading selection | <!-- [week6](week6) --> |
| 7 | Annotated references | <!-- [week7](week7) --> |
| 8 | Script development  | <!-- [week8](week8) --> |
| 9 | Record/edit podcast | <!-- [week9](week9) --> |
| 10 | Edit, write abstract, submit; closing reflective statement (w. ref to other courses/position on learning) | <!-- [week10](week10) --> |


To learn more about Quarto websites visit <https://quarto.org/docs/websites>.
